// <auto-generated />
using System;
using Lab__2_.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lab__2_.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230524130841_changed_rentalForm")]
    partial class changed_rentalForm
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lab_2.Models.AdministratorVm", b =>
                {
                    b.Property<int>("AdministratorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdministratorID"));

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdministratorID");

                    b.ToTable("Administrators");
                });

            modelBuilder.Entity("Lab_2.Models.CarsVm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDamaged")
                        .HasColumnType("bit");

                    b.Property<decimal>("RentPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("RentalFormVmId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RentalFormVmId")
                        .IsUnique()
                        .HasFilter("[RentalFormVmId] IS NOT NULL");

                    b.ToTable("Cars");

                    b.HasDiscriminator<string>("Discriminator").HasValue("CarsVm");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Lab_2.Models.ClientVm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PassportNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RentalFormVmId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RentalFormVmId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Lab_2.Models.RentalFormVm", b =>
                {
                    b.Property<int>("RentalFormID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RentalFormID"));

                    b.Property<int>("CarID")
                        .HasColumnType("int");

                    b.Property<int>("ClientID")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsConsidered")
                        .HasColumnType("bit");

                    b.Property<string>("RejectionReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RentalFormID");

                    b.HasIndex("ClientID");

                    b.ToTable("RentalForm");

                    b.HasDiscriminator<string>("Discriminator").HasValue("RentalFormVm");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Lab_2.Models.RentalCarVm", b =>
                {
                    b.HasBaseType("Lab_2.Models.CarsVm");

                    b.Property<string>("CarImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("RentalCarVm");
                });

            modelBuilder.Entity("Lab_2.Models.OrderVm", b =>
                {
                    b.HasBaseType("Lab_2.Models.RentalFormVm");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<int>("RentalTime")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasDiscriminator().HasValue("OrderVm");
                });

            modelBuilder.Entity("Lab_2.Models.CarsVm", b =>
                {
                    b.HasOne("Lab_2.Models.RentalFormVm", "RentalFormVm")
                        .WithOne("Car")
                        .HasForeignKey("Lab_2.Models.CarsVm", "RentalFormVmId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("RentalFormVm");
                });

            modelBuilder.Entity("Lab_2.Models.ClientVm", b =>
                {
                    b.HasOne("Lab_2.Models.RentalFormVm", "RentalFormVm")
                        .WithMany()
                        .HasForeignKey("RentalFormVmId");

                    b.Navigation("RentalFormVm");
                });

            modelBuilder.Entity("Lab_2.Models.RentalFormVm", b =>
                {
                    b.HasOne("Lab_2.Models.ClientVm", "Client")
                        .WithMany("ClientOrders")
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Lab_2.Models.ClientVm", b =>
                {
                    b.Navigation("ClientOrders");
                });

            modelBuilder.Entity("Lab_2.Models.RentalFormVm", b =>
                {
                    b.Navigation("Car")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
